### ISSUE TITLE
Weakly clean but not clean

### ISSUE THREAD

**Issue by Jeremy-Rickard** [rschwiebert/dart_data#1]
On the "Suggested additions" page, an example of a weakly clean but not clean ring is asked for.

On page 1599 of J. Ster. "Corner rings of a clean ring need not be clean" (2012) a proof is given that Ring 70 (Bergman's exchange ring that isn't clean) is weakly clean, so assuming it is correct, then this provides an example. 

But on the "Ring detail" page for Ring 70, that paper is already cited, so maybe you know of some problem with the proof?

By the way, I got quite confused by the fact that there are two meanings of "weakly clean" in the literature, which are not equivalent. The other one is that every element is either the sum u+e _or the difference_ u-e of a unit u and an idempotent e. Probably you're aware of this, but if not then it might be something to be careful about.

**Comment by rschwiebert** [comment]
The paper's already cited because its main example was used for https://ringtheory.herokuapp.com/rings/ring/67/ . At this point I do not know of any problems with Ster's work, but when I do find something I put it in the errata part of the website.

I did not know of the difference definition, but I think the two definitions are manifestly equivalent, no?
Suppose all elements are u+e clean.   Then for an arbitrary element x, -x=u+e, implies x=(-u)-e which is a difference of a unit and idempotent.   Likewise if they are all u-e clean, then for a given element -x=u-e -> x=-u+e is clean, a sum of a unit and idempotent.

I will look into the first thing!  In focusing on the main example I probably overlooked that comment.

**Comment by Jeremy-Rickard** [comment]
Sorry, I didn't write that very clearly. I meant that every element is either a sum u+e or a difference u-e, but some elements can be sums and others can be differences.

I found a simple example of "weakly clean but not clean" in a paper that used that definition of "weakly clean". Let R be the ring of rationals whose denominator is divisible by neither 3 nor by 5. It's not clean, since 6 cannot be written as u+e, but is weakly clean by this alternative definition (for any x, at least one of x-1, x, x+1 must be a unit). I didn't realise they were using a different definition, and was confused becuase I was fairly sure that I could show that it is not weakly clean. And indeed, if you use DaRT's definition, it is **not** weakly clean.

**Comment by rschwiebert** [comment]
Oh!  Yeah, I've never heard that one...  I'll stay on guard for that confusion in the future.
