### ISSUE TITLE
Ring 103 (Hochster's connected, nondomain, locally-domain ring) description

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#18]
https://github.com/rschwiebert/dart_data/blob/785b8987539e1a37eb8da2c64bd4e7729ffd163b/db/ringapp/ring/RING_000103/data.yaml#L3 

Needs a good description or expanded details page.

**Comment by dyunov** [comment]
Description: Let $L$ be the commutative semigroup with underlying set $\Bbb Q \times \Bbb N$, where $(x,m) (x + z,n) = (x,m)$ if $z > 0$, and $(x,m) (x,n) = (x, m+n)$. Adjoin a neutral element to $L$ and denote the resulting monoid by $M$. Then the ring is $R = \Bbb Q[M]$.

Remarks
---
"Cardinality" is already filled in as $\aleph_0$, so I had to specialize to $\Bbb Q$ for both the ordered set and $K$.

$R$ has quite a large automorphism group: for every [monotonically](https://mathoverflow.net/questions/42460/) increasing [function](https://mathoverflow.net/questions/120333/) $f: \Bbb Q \to \Bbb Q$, the $\Bbb Q$-linear map $t_f: R \to R$, $(x,n) \mapsto (f(x), n)$, is an $R$-automorphism.

If the italicized condition in the following Lemma 1 could be removed, we'll get a description of units and of $J(R)$.

Denote the augmentation ideal of $R$ by $wR$, and the subring $\bigoplus\limits_{i=0}^\infty \Bbb Q (q, 1)^i$ by $R_q$.
For any $q \in \Bbb Q$, define the $q$-part $P_q(r)$ of $r \in R$ as the linear combination of terms $(q, n)$ that occur in $r$, such that $r = \sum\limits_{q \in \Bbb Q} P_q(r)$.
Let $\mu(r) = \min\limits_{(x, n)\text{ occurs in }r} x$.

**Lemma 1.** If there exists a unit $r \in R \setminus \Bbb Q$ *"such that* $r' = r - P_{\mu(r)}(r) \not \in wR$", then there exists a unit in $R_q \setminus \Bbb Q$.
*Proof.* We have $r \not \in wR$, and $r$ must contain a nonzero constant term $c$: otherwise $r (1 - (-N, 1)) = 0$ for a sufficiently large positive integer $N$.
WLOG $c = 1$. Then $r' (1 + \lambda P_{\mu(r)}(r)) = r' + \rho \lambda P_{\mu(r)}(r)$, where $0 \not = \rho$ is the image of $r'$ under the augmentation map. If we take $\rho = 1/\lambda$, we get $r$, so then $(1 + \lambda P_{\mu(r)}(r))$ would be invertible too.

**Lemma 2.** There are no units of $R$ in $R_q \setminus \Bbb Q$.
*Proof.* Suppose $r$ is such a unit. By uniqueness of inverses $r^{-1}$ has to be invertible in $R_q$ too, as the automorphism defined by $f$: $x \mapsto q + 2 (x - q)$ fixes $r$ and has to fix $r^{-1}$. However $R_q \cong \Bbb Q[t]$.

Properties
---

- :x: $I_0$. Has nontrivial ideals: $((0,1))$ does not contain $1$.
- :x: ACC/DCC annihilator. Take elements of form $1 - (y,1)$, $y \in \Bbb Z$.
- :x: ACC principal. Elements $(y,1)$, $y \in \Bbb Z$.
- ✔️ countable.
- :x: dual. The annihilator of the principal ideal $((0,2))$ seems to be generated by $1 - (x,y)$ for positive $x$, but all these elements also annihilate $(0,1)$.
- :x: local. $(1 - (0,1)) + (0,1)$ is invertible.

Additional remarks
---
In the countable property definition, it would be better to write "The underlying set of the ring is **at most** countable" (`allprops.svg` shows "finite ===> countable").

**Comment by rschwiebert** [comment]
@dyunov Re: ring 86's commutativity: This is a great example of one of Bergman's examples that I find so abstruse I feel uncomfortable deciding something even THAT simple.  I suppose it is NOT commutative?

**Comment by rschwiebert** [comment]
@dyunov  Yes, I'm convinced by the proof about units. I was thinking along the lines of using the linear order on $L$, but it's too fine: thinking instead of a degree based on the rational part only definitely makes sense.
