### ISSUE TITLE
Get ring 67 (Šter's clean ring with non-clean corner rings) %-complete over 50%

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#21]
https://github.com/rschwiebert/dart_data/blob/785b8987539e1a37eb8da2c64bd4e7729ffd163b/db/ringapp/ring/RING_000067/properties.yaml

This ring has the distinction of having the lowest %-complete for its properties.  Let's try to improve that to be over 50%.

**Comment by dyunov** [comment]
- :x: Abelian. $E_{11}$ (the identity infinite matrix from $R_{70}$ on the (1,1) position in $R$) is not central.
- :x: Dedekind finite. The classical example put into $E_{11}$ with other diagonal elements being the identity transformations works fine.
- ✔️ IBN. I think $R_{67}/(I)$ (see definition of $I \lhd R_{70}$ on p1598 of Ster's paper) should be isomorphic to the unitized direct limit of square matrix rings over the field $\Bbb F_2((X))$. By Th2.3 [here](https://core.ac.uk/download/pdf/82570195.pdf) IBN is conserved by direct limits.
- :x: IC. Same technique as in other known examples should work: take the zero right ideal and the first row for $B$.
- :x: NI. $E_{12}$, $E_{21}$.
- ✔️ von Neumann regular. $R_{70}$ is von Neumann regular, so are finite matrix rings over it, and their direct limit.
- :x: countable. The first few rows in the construction of $R_{70}$ can be completely arbitrary.
- :x: orthogonally finite. $\{E_{ii}\}$.
- :x: reversible. $E_{11} E_{21} = 0 \not = E_{21} E_{11}$.
- :x: semicommutative. $E_{12}E_{11} = 0 \not = E_{12}E_{21}E_{11}$.
- :x: symmetric. $E_{11}E_{21}E_{12} = 0 \not = E_{11}E_{12}E_{21}$.

Since vNr $\Rightarrow$ semiprimitive, these should imply a lot more properties that are currently unknown. I stopped at an arbitrary point; I plan to go through the list again when the property list is cleaned up by logic.

Comments
---
Does DaRT have the unitized direct limit of matrix rings over a field?
The page title "DaRT - Ring detail" is uninformative if you have multiple ring pages open. Would it be possible to display at least the ring number, say "DaRT - Ring detail - Ring 67", like in the properties? This way new users also won't be bewildered when the ring numbers start appearing in the formulae. (A few years ago, I was :-) )
The Toeplitz-Jacobson algebra seems to be isomorphic to its opposite by swapping the variables. Lam I p184 (and DaRT) only mention it to be *left* primitive.

**Comment by rschwiebert** [comment]
> The page title "DaRT - Ring detail" is uninformative if you have multiple ring pages open. Would it be possible to display at least the ring number, say "DaRT - Ring detail - Ring 67", like in the properties? 

I will be glad to do something about this. I have always been dissatisfied with it.

**Comment by dyunov** [comment]
I think LaTeX can't be rendered in a browser tab caption. (Well, if it was possible, we'd likely see that on MSE/MO...) And there are quite a lot of rings with non-textual names in DaRT.
Both "Details for R_{n}" and "Profile of R_{n}" would IMO be fine.
Another option: maybe start the caption with the ring/property name ("R_{67} - Ring detail - DaRT" or "lift/rad - Property detail - DaRT"), so when someone has a lot of tabs, the most important information gets out of the view last.

**Comment by dyunov** [comment]
Regarding the
> unitized direct limit of matrix rings over a field

That seems to be $R_{93}$. (Isn't the center of $T$ there just the set of scalar matrices, as in usual matrix rings?) Then, in $R_{142}$, one can set $B = R_{93}$.

**Comment by rschwiebert** [comment]
@dyunov  For IBN, we can just observe that $R/T$ ($T$ as in the definition) is a field, so $R$ has the IBN.

**Comment by dyunov** [comment]
I agree, that's much more simple for IBN.
The upper row of $T$ is the principal right ideal $E_{11} R$ that has a complement $(I - E_{11}) R$. But as a right ideal, $(I - E_{11}) R$ seems to be isomorphic to $R_R$. So we have $R_R \cong 0 \oplus R_R \cong E_{11} R \oplus R_R$, and clearly $0 \not \cong E_{11} R$.
(Wouldn't this somehow contradict IBN, though..?)
