### ISSUE TITLE
Ring 83 (Šter's counterexample showing "clean" is not Morita invariant) description

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#22]
https://github.com/rschwiebert/dart_data/blob/785b8987539e1a37eb8da2c64bd4e7729ffd163b/db/ringapp/ring/RING_000083/data.yaml#L3

Description needs to be written or an expanded details page developed.

**Comment by dyunov** [comment]
Description
---
Let $[F':F]=n$ be a field extension, $S \supset S'$ the full $F$- and $F'$-linear rings of the countable-dimensional $F'$-vector space $V$, and their ideals $I \supset I'$ of transformations with finite-dimensional range. Then the sum $T = S' + I$ is a subring in $S$.

The idempotent $e = E_{11}$ of $S'$ is primitive in $S'$ and is a sum of $n$ primitive orthogonal idempotents $e_1, \ldots, e_n$ in $S$ and $T$. Let $C$ be the corner ring $(e_n + 1 - e) T (e_n + 1 - e)$. Then the ring $R_{83}$ is defined as the set of all countable-sized column-finite matrices $M$ over $C$ with the following property: there exists an integer $N = N(M)$ such that the row $M_{N,\*} = [m_{N1}, m_{N2},\ldots]$ has all $m_{Ni} \in F = F1 \subset C$, and all the next rows are shifts of $M_{N,\*}$, namely, $M_{N + k, \*} = [0, \ldots, 0, m_{N1}, m_{N2},\ldots]$ ($k$ zeros) for every positive integer $k$.

Cf. [$R_{67}$](https://ringtheory.herokuapp.com/rings/ring/67/) and [$R_{70}$](https://ringtheory.herokuapp.com/rings/ring/70/expanded-details/).

Explanation
---
The difference with $R_{70}$ is in that the top rows (ones that are above the "Toeplitz" part of the infinite matrix) are now allowed to lie in a fixed $F$-algebra, rather than just $F$ (see p22). On p33, the algebra is chosen to be the ring $R_1$ from p20 (the symbol $R$ denotes a different ring in Section 3 from what is taken as $R$ in Section 6). I renamed $R$ to $T$ and $R_1$ to $C$.
Ster defines $V$ just as infinite-dimensional, not necessarily countable-dimensional. On the expanded details page for $R_{70}$, it is written "infinite" but probably meant "countable".
In $R_{67}$ the Bergman's Toeplitz-like ring appears in the "scalars" of a matrix ring direct limit. Here the construction is done vice versa: the "scalars" are subrings of a $\Bbb{CF}_{\Bbb N}(F')$, but the "large structure" is Toeplitz-like.

Properties
---

Each property in my first #21 comment translates to this situation directly, except IBN and vNr:

>- :x: Abelian. $E_{11}$ (the identity infinite matrix from $R_{70}$ on the (1,1) position in $R$) is not central.
>- :x: Dedekind finite. The classical example put into $E_{11}$ with other diagonal elements being the identity transformations works fine.
>- :x: IC. Same technique as in other known examples should work: take the zero right ideal and the first row for $B$.
>- :x: NI. $E_{12}$, $E_{21}$.
>- :x: countable. The first few rows in the construction can be completely arbitrary.
>- :x: orthogonally finite. $\{E_{ii}\}$.
>- :x: reversible. $E_{11} E_{21} = 0 \not = E_{21} E_{11}$.
>- :x: semicommutative. $E_{12}E_{11} = 0 \not = E_{12}E_{21}E_{11}$.
>- :x: symmetric. $E_{11}E_{21}E_{12} = 0 \not = E_{11}E_{12}E_{21}$.

Maybe someday I'll try to adapt Goodearl p47 to vNr here...

**Comment by rschwiebert** [comment]
My head must be on wrong:
> The idempotent $e = E_{11}$ of $S'$ is primitive in $S'$ and is a sum of $n$ primitive orthogonal idempotents $e_1, \ldots, e_n$ in $S$ and $T$.

Isn't this $e$ even an irreducible idempotent in all three rings already, so that it's not a sum of nontrivial primitive orthogonal idempotents?

**Comment by dyunov** [comment]
The confusion again stems from my poor wording, but I do not know how to reexpress that idea in a clear and concise manner.
For a finitary version, if one fixes a basis $w_1, \ldots, w_n$ of $F'$ over $F$, one obtains an injective $F$-linear map $\phi: F' \to M_n(F)$.
Then a $k \times k$-matrix over $F'$ corresponds to an $nk\times nk$-matrix over $F$, i.e. there is an injective map $\phi_k: M_k(F') \to M_{nk}(F)$.
Now the $E_{11}$ in the cited fragment refers to $E_{11}$ of $M_k(F')$. But its image would be an $n$-dimensional identity submatrix of $M_{nk}(F)$.
In $R_{83}$, $k$ is just $\omega$ rather than a finite number.

**Comment by rschwiebert** [comment]
Thanks for explaining: yeah this is just me forgetting what the obvious embedding $S'\subseteq S$ should look like.   That makes sense...

**Comment by dyunov** [comment]
Oops, I read only the first version of your comment and completely missed the edited one!

---
> Does the first paragraph sound like a reasonable way to misunderstand things?

$F'$ is the *larger* field, otherwise everything seems fine. We can specialize $F = \Bbb R$, $F' = \Bbb C$. Then $V = \Bbb C^\infty$, $S = End_{\Bbb R} V \supset End_{\Bbb C} V = S'$. If we fix $F' \hookrightarrow M_2(F)$, $a + bi \mapsto$ <img src="https://github.com/rschwiebert/dart_data/assets/89836711/4243ca49-120d-4581-8962-3e9ce9161063" height="40">, then the matrices of $S'$ in $S$ are block-2x2 with blocks of this form.

**Comment by rschwiebert** [comment]
Splitting out the properties for later review.
