### ISSUE TITLE
Add new example to show $\pi$-regular, T-nilpotent radical does not pass to arbitrary direct products

### ISSUE THREAD

**Issue by rschwiebert** [rschwiebert/dart_data#46]
Add $\prod\limits_{i = 2}^\infty \Bbb R[x_n]/(x_n^n)$ (or a variation thereof) to act as a counterexample that pi-regularity and T-nilpotence do not pass to arbitrary direct products.

**Comment by dyunov** [comment]
I think the choice of $\Bbb Q$ instead of $\Bbb R$ would be more in line with rings already in DaRT.

Preliminaries
---

- The Jacobson radical of this ring is principal and generated by $(x_2,x_3,x_4,x_5,\ldots)$.
- $\Bbb Q[x]/(x^n)$ is uniserial.
- Prime ideals in the ring are maximal. (Is there a name for this property? All I know is integer rings of number fields also qualify.)

Properties
---

- [ ] ✔ commutative.
- [ ] ✔ countable.
- [ ] ❌ orthogonally finite.
- [ ] ✔ stably finite. "Commutative" implies "stably finite" by Lam II (1.12) (however `commrings.svg` contains it near the bottom!) BTW by (1.10) this property is ✔ P.
- [ ] ✔ stable range 1. This is ✔ P, as $xa+b=1$ implies the same for every projection, and we can assemble $y$ and the unit componentwise. The property is also Morita invariant by Theorem 5.6 from the "Crash course".
- [ ] ❌ $\pi$-regular, strongly $\pi$-regular, nil radical. Take $(x_2,x_3,x_4,x_5,\ldots)$.
- [ ] ❌ semilocal. $R/J(R) = \prod\limits_{i = 1}^\infty \Bbb Q$.
- [ ] ✔ self-injective. As it is stable under products, consider $\Bbb Q[x]/(x^n)$. Showing QF would be enough, but it follows from Logic 79 since $l(x^k) = (x^{n-k})$.
- [ ] ❌ semiprime. Clear.
- [ ] ✔ distributive. This property is ✔ P by "ideals of product = products of ideals" and the characterization of distributive lattices as subdirect products of the two-element chain; and the factors are uniserial.
- [ ] ✔ nonzero socle, essential socle. I think these properties are ✔ P, and in our case the socle is apparently generated by $\\{x_n^{n-1}\\}$.
- [ ] ❌ f.g. socle. See above.
- [ ] ❌ Kasch. The direct sum in the direct product has zero annihilator, which contradicts the annihilator conditions (Lam II (8.29)(4)).
- [ ] ✔ catenary. $n = 1$.

Comments
---
- Von Neumann regular is known to be ✔ P.
- I don't get why J-1 implies J-0, unless the subset in J-1 is also meant to be nonempty. The prime ideal structure would give information on the J-... property series (apparently $\text{Spec } R$ is a countable discrete space since every point is closed), but I'm not at all familiar with these definitions.

**Comment by rschwiebert** [comment]
> Prime ideals in the ring are maximal.

I think that is not true. For commutative rings, prime ideals are maximal (i.e. it's got krull dimension 0) exactly when $R/J(R)$ is von Neumann regular and $J(R)$ is a nil ideal. For this ring, J(R) is not nil, considering the generator you gave.
