### ISSUE TITLE
Quotient rings

### ISSUE THREAD

**Issue by lenaread** [rschwiebert/dart_data#8]
Attached are properties of quotient rings of free algebras and polynomial rings that are not confirmed on DaRT. The pdf Quotient ring properties acts as a contents for the others.

[K[X,Y]-(X^2,XY).pdf](https://github.com/rschwiebert/dart_data/files/9352811/K.X.Y.-.X.2.XY.pdf)
[Q(a,b)-(a^2).pdf](https://github.com/rschwiebert/dart_data/files/9352812/Q.a.b.-.a.2.pdf)
[Quotient_ring_properties.pdf](https://github.com/rschwiebert/dart_data/files/9352813/Quotient_ring_properties.pdf)
[Z(X,Y)-(Y^2,YX).pdf](https://github.com/rschwiebert/dart_data/files/9352814/Z.X.Y.-.Y.2.YX.pdf)
[Z[X]-(X^2-1).pdf](https://github.com/rschwiebert/dart_data/files/9352815/Z.X.-.X.2-1.pdf)

Thank you for taking the time to look through my work. Let me know if there are any issues.

**Comment by rschwiebert** [comment]
Hi!  As with your compatriot Guillermo, I thank you and caution that I will be somewhat slow resolving these.  At the moment there is only me to review and enter things, and sometimes it requires some footwork before things are resolved.  I look forward to working with you two again in the future.

**Comment by rschwiebert** [comment]
I have not thought about free algebra quotients being isomorphic to their opposites before, but I suppose the map reversing the order of words does the trick?  And then a quotient of a free algebra would have that property as long as reversal preserves the relations, as in this case?

**Comment by rschwiebert** [comment]
The argument of strong connectivity for $\mathbb Q\langle a , b \rangle /(a^2)$ is not sufficient as written, I think.  But the idea using degrees should still go through. Here is the argument that seems most convincing to me.

The words in $a$ and $b$, along with the empty word, form a basis for the free algebra, and the ones without $a^2$ anywhere form a basis for this quotient. Notice that in the quotient the product of any two words $x,y$ in the symbols $a$ and $b$ will have length $len(xy)=len(x)+len(y)$ or $len(x)+len(y)-2$ according to whether or not $x$ ends in $a$ and $y$ begins with $a$.  Then, the maximum length of a word appearing in the expression for an element, we have a sort of degree.

Suppose for a moment we have an idempotent of degree greater or equal to $1$. Since the degree of an idempotent must remain the same after having been squared, you'd need an element with maximum degree satisfying $d=2d-2$, in other words, $d=2$.  But as noted earlier, one can only obtain this degree reduction if the elements of degree 2 begin and end with $a$, but that would mean they are all $a^2=0$, which is an absurdity.

The only idempotents left to consider have degree $0$, which we know are just 1 and 0.

**Comment by rschwiebert** [comment]
You proved more than $\mathbb Z\langle x, y \rangle/(y^2,yx)$ having NI.  You proved it is 2-primal. You showed $(y)$ is a completely prime ideal, and conversely every prime ideal must contain $(y)$ because it squares to $\{0\}$.  Thus $(y)$ is the unique minimal prime ideal (and it is completely prime.)
